# vcluster:
#   image: rancher/k3s:v1.23.3-k3s1 # be sure that use same cluster version either change an image tag
#   extraArgs:
#     - --service-cidr=10.100.0.0/16 # THE CLUSTER SERVICE CIDR HERE ( you can find here https://github.com/loft-sh/virtual-cluster#install how to get it)
# storage:
#   size: 1Gi
controlPlane:
  # Distro holds virtual cluster related distro options. A distro cannot be changed after vCluster is deployed.
  distro:
    # K8S holds K8s relevant configuration.
    k8s:
      image:
        tag: "v1.33.0"
